-d /home/clar/Sistem Programlama Proje/picorv32_assembler_project_bundle_v2/picorv32_assembler_project/impl/gwsynthesis/project.vg
-p GW1NR-9-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/clar/Sistem Programlama Proje/picorv32_assembler_project_bundle_v2/picorv32_assembler_project/fpga/constraints/tangnano9k.cst
-cfg /home/clar/Sistem Programlama Proje/picorv32_assembler_project_bundle_v2/picorv32_assembler_project/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
